name: Docker Smart Build
description: Smartly builds a docker image
runs:
  using: "docker"
  image: "docker://slalomggp:dataops:latest-dev"
  args:
    - dockerutils
    - smart_build
    - --dockerfile_path=${{ inputs.imageName }}
    - --existing_tag=${{ inputs.existingTag }}
    - --tag_as=${{ inputs.tagAs }}
  env:
    DOCKER_USER: "{{ inputs.dockerUser }}"
    DOCKER_PASSWORD: "{{ inputs.dockerPass }}"
inputs:
  imageName:
    description: "The name of the image (without tags)"
    required: true
  existingTag:
    description: "The name of the tag that already exists"
    required: true
  tagAs:
    description: "The name of the new tag (or a comma-separated list of tags)"
    required: true
  dockerUser:
    description: "The name of the new tag (or a comma-separated list of tags)"
    required: false
    default: ""
  dockerPass:
    description: "The name of the new tag (or a comma-separated list of tags)"
    required: false
    default: ""
branding:
  icon: chevrons-right
  color: blue
