name: CI/CD Builds

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - docs/**.md
      - "*.md"

jobs:
  python_dataops_build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - 3.7
        # - 3.8  # Requires Spark 3.0 (still in preview)
        #        # Related PR: https://github.com/apache/spark/pull/26194
    steps:
      - name: Clone git repo
        uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      # - name: Install dependencies (apt-get)
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libsasl2-dev
      - name: Install dependencies (python pip)
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.local-dev.txt
          pip3 install flake8 pytest
      - name: Install slalom.dataops
        run: |
          python3 setup.py install
      - name: Test CLI shortcuts
        run: |
          set -v
          s-spark --help
          s-infra --help
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest

  pypi_publish:
    runs-on: ubuntu-latest
    needs:
      - python_dataops_build
    steps:
      - name: Clone git repo
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Push to PyPi (https://pypi.org/project/slalom.dataops/)
        env:
          BRANCH_NAME: ${{ github.ref }}
          PYPI_USER: ${{ secrets.PYPI_USER }}
          PYPI_PASS: ${{ secrets.PYPI_SECRET }}
        run: |
          echo -e "Installing twine...\n\n"
          pip install twine
          echo -e "\nCreating setup package...\n\n"
          python setup.py sdist
          echo -e "\nPublishing to version ref '$VERSION'...\n\n"
          twine upload -u $PYPI_USER -p $PYPI_PASS dist/*
      # - name: Test install (pip install slalom.dataops --pre)
      #   run: |
      #     pip install --no-cache-dir slalom.dataops==$(cat VERSION) --pre
      # - name: Test uninstall (pip uninstall slalom.dataops)
      #   run: |
      #     pip uninstall -y slalom.dataops
      # - name: Test full install (pip install --pre w/ extras)
      #   run: |
      #     pip install slalom.dataops[AWS,Azure,Pandas,Spark]==$(cat VERSION) --pre

  docker_spark:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: slalomggp/spark
      DOCKERFILE_PATH: containers/docker-dataops/spark.Dockerfile
    steps:
      - name: Clone git repo
        uses: actions/checkout@v1
      - name: Smart build and push (${{ env.IMAGE_NAME }})
        uses: aaronsteers/dock-r/.github/actions/docker-smart-build@master
        with:
          dockerfilePath: ${{ env.DOCKERFILE_PATH }}
          tagAs: ${{ env.IMAGE_NAME }}:latest-dev,${{ env.IMAGE_NAME }}:commit-${{ github.sha }}
          dockerUser: ${{ secrets.DOCKER_USER }}
          dockerPassword: ${{ secrets.DOCKER_SECRET }}
          ignoreCaches: 0
  # docker_dbt_min:
  #   runs-on: ubuntu-latest
  #   env:
  #     IMAGE_NAME: slalomggp/dbt
  #     DOCKERFILE_PATH: containers/docker-dataops/dbt.Dockerfile
  #     TAG_PREFIX: min-
  #   steps:
  #     - name: Clone git repo
  #       uses: actions/checkout@v1
  #     - name: Smart build and push (slalom/dbt)
  #       uses: aaronsteers/dock-r/.github/actions/docker-smart-build@master
  #       with:
  #         dockerfilePath: ${{ env.DOCKERFILE_PATH }}
  #         tagAs: ${{ env.IMAGE_NAME }}:${{ env.TAG_PREFIX }}latest-dev,${{ env.IMAGE_NAME }}:${{ env.TAG_PREFIX }}commit-${{ github.sha }}
  #         dockerUser: ${{ secrets.DOCKER_USER }}
  #         dockerPassword: ${{ secrets.DOCKER_SECRET }}
  #         additionalArgs: >
  #           --build-arg source_image=python:3.7
  #           --build-arg dbt_spark_source=git+https://github.com/fishtown-analytics/dbt-spark@master
  #         ignoreCaches: 0
  # docker_dbt:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - docker_spark
  #   env:
  #     IMAGE_NAME: slalomggp/dbt
  #     DOCKERFILE_PATH: containers/docker-dataops/dbt.Dockerfile
  #   steps:
  #     - name: Clone git repo
  #       uses: actions/checkout@v1
  #     - name: Smart build and push (slalom/dbt)
  #       uses: aaronsteers/dock-r/.github/actions/docker-smart-build@master
  #       with:
  #         dockerfilePath: ${{ env.DOCKERFILE_PATH }}
  #         tagAs: ${{ env.IMAGE_NAME }}:latest-dev,${{ env.IMAGE_NAME }}:commit-${{ github.sha }}
  #         dockerUser: ${{ secrets.DOCKER_USER }}
  #         dockerPassword: ${{ secrets.DOCKER_SECRET }}
  #         additionalArgs: >
  #           --build-arg source_image=slalomggp/spark:commit-${{ github.sha }}
  #           --build-arg dbt_spark_source=git+https://github.com/fishtown-analytics/dbt-spark@master
  #         ignoreCaches: 0
  # docker_dataops:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - python_dataops_build
  #     - docker_spark
  #     - docker_dbt
  #   env:
  #     IMAGE_NAME: slalomggp/dataops
  #     DOCKERFILE_PATH: ./Dockerfile
  #   steps:
  #     - name: Clone git repo
  #       uses: actions/checkout@v1
  #     - name: Smart build and push (${{ env.IMAGE_NAME }})
  #       uses: aaronsteers/dock-r/.github/actions/docker-smart-build@master
  #       with:
  #         dockerfilePath: ${{ env.DOCKERFILE_PATH }}
  #         tagAs: ${{ env.IMAGE_NAME }}:latest-dev,${{ env.IMAGE_NAME }}:commit-${{ github.sha }}
  #         dockerUser: ${{ secrets.DOCKER_USER }}
  #         dockerPassword: ${{ secrets.DOCKER_SECRET }}
  #         additionalArgs: --build-arg source_image=slalomggp/dbt:commit-${{ github.sha }}
  #         ignoreCaches: 0
