name: Docker Publish (latest)

on:
  push:
    branches:
      - master

jobs:
  docker_dataops_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone git repo
        uses: actions/checkout@v1
      - name: Retag Dataops image
        uses: ./.github/actions/docker-retag
        with:
          imageName: slalomggp/dataops
          existingTag: commit-${{ github.sha }}
          tagAs: latest
          dockerUser: ${{ secrets.DOCKER_USER }}
          dockerPassword: ${{ secrets.DOCKER_SECRET }}
  docker_ci_builder_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone git repo
        uses: actions/checkout@v1
      - name: Retag Dataops image
        uses: ./.github/actions/docker-retag
        with:
          imageName: slalomggp/ci-builder
          existingTag: commit-${{ github.sha }}
          tagAs: latest
          dockerUser: ${{ secrets.DOCKER_USER }}
          dockerPassword: ${{ secrets.DOCKER_SECRET }}
  docker_spark_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone git repo
        uses: actions/checkout@v1
      - name: Retag Dataops image
        uses: ./.github/actions/docker-retag
        with:
          imageName: slalomggp/spark
          existingTag: commit-${{ github.sha }}
          tagAs: latest
          dockerUser: ${{ secrets.DOCKER_USER }}
          dockerPassword: ${{ secrets.DOCKER_SECRET }}
  docker_dbt_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone git repo
        uses: actions/checkout@v1
      - name: Retag Dataops image
        uses: ./.github/actions/docker-retag
        with:
          imageName: slalomggp/dbt
          existingTag: commit-${{ github.sha }}
          tagAs: latest
          dockerUser: ${{ secrets.DOCKER_USER }}
          dockerPassword: ${{ secrets.DOCKER_SECRET }}
  docker_singer_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone git repo
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install slalom.dataops
        run: python3 setup.py install
      - name: Login to docker
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_SECRET }}
      - name: Build and push all singer images
        run: cd containers/singer && s-tap build_all_images --push
      - name: Print list of images
        run: docker image ls
