name: Publish to PyPi and Dockerhub

# temporary for testing
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - docs/**.md
      - "*.md"

# on:
#   release:
#     types: [published]

jobs:
  pypi_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone git repo
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Push to PyPi (https://pypi.org/project/slalom.dataops/)
        env:
          VERSION: ${{ github.ref }}
          PYPI_USER: ${{ secrets.PYPI_USER }}
          PYPI_PASS: ${{ secrets.PYPI_SECRET }}
        run: |
          echo -e "Installing twine...\n\n"
          pip install twine
          echo -e "\nCreating setup package...\n\n"
          python setup.py sdist
          echo -e "\nPublishing to version ref '$VERSION'...\n\n"
          twine upload -u $PYPI_USER -p $PYPI_PASS dist/*
      - name: Test install (pip install slalom.dataops)
        run: |
          pip install slalom.dataops
      - name: Test uninstall (pip uninstall slalom.dataops)
        run: |
          pip uninstall -y slalom.dataops
      - name: Test full install (pip install w/ extras)
        run: |
          pip install slalom.dataops[Azure,AWS,Docker,Pandas,Spark]

  docker_dataops_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone git repo
        uses: actions/checkout@v1
      - name: Retag Dataops image
        uses: ./.github/actions/docker-retag
        with:
          imageName: slalomggp/dataops
          existingTag: commit-${{ github.sha }}
          tagAs: latest
          dockerUser: ${{ secrets.DOCKER_USER }}
          dockerPass: ${{ secrets.DOCKER_SECRET }}
  docker_ci_builder_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone git repo
        uses: actions/checkout@v1
      - name: Retag Dataops image
        uses: ./github/actions/docker-retag
        with:
          imageName: slalomggp/ci-builder
          existingTag: commit-${{ github.sha }}
          tagAs: latest
          dockerUser: ${{ secrets.DOCKER_USER }}
          dockerPass: ${{ secrets.DOCKER_SECRET }}
  docker_spark_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone git repo
        uses: actions/checkout@v1
      - name: Retag Dataops image
        uses: ./.github/actions/docker-retag
        with:
          imageName: slalomggp/spark
          existingTag: commit-${{ github.sha }}
          tagAs: latest
          dockerUser: ${{ secrets.DOCKER_USER }}
          dockerPass: ${{ secrets.DOCKER_SECRET }}
  docker_dbt_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone git repo
        uses: actions/checkout@v1
      - name: Retag Dataops image
        uses: ./.github/actions/docker-retag
        with:
          imageName: slalomggp/dbt
          existingTag: commit-${{ github.sha }}
          tagAs: latest
          dockerUser: ${{ secrets.DOCKER_USER }}
          dockerPass: ${{ secrets.DOCKER_SECRET }}
