name: Docker Retag
description: Smartly retags an existing docker image
runs:
  using: "docker"
  image: "docker://slalomggp/dataops:latest-dev"
  args:
    - dockerutils
    - remote_retag
    - --image_name=${{ inputs.imageName }}
    - --existing_tag=${{ inputs.existingTag }}
    - --tag_as=${{ inputs.tagAs }}
  env:
    DOCKER_USER: "{{ inputs.dockerUser }}"
    DOCKER_PASSWORD: "{{ inputs.dockerPass }}"
inputs:
  imageName:
    description: "The name of the image (without tags)"
    required: true
  existingTag:
    description: "The name of the tag that already exists"
    required: true
  tagAs:
    description: "The name of the new tag (or a comma-separated list of tags)"
    required: true
  dockerUser:
    description: "Docker user for login"
    required: false
    default: ""
  dockerPass:
    description: "Docker password for login"
    required: false
    default: ""
branding:
  icon: anchor
  color: blue
